name: compile compressionlib

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macOS-latest]
            platform: [x32, x64]
    steps:
    - uses: actions/checkout@v2
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.4.1
      if: matrix.os == 'windows-latest'

    - name: compile compressionlib windows
      shell: cmd
      run: |
        cd compression\\new
        compile.bat
        mv compressionlib.dll ..\\bin\\compressionlib-${{ matrix.os }}-${{ matrix.platform }}.dll
      if: matrix.os == 'windows-latest'
    
    - name: compile compressionlib unix-like
      run: |
        cd compression/new
        chmod +x compile.sh
        ./compile.sh
        mv compressionlib.so ../bin/compressionlib-${{ matrix.os }}-${{ matrix.platform }}.so
      shell: bash
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'

    - name: archive windows
      uses: actions/upload-artifact@v2
      if: matrix.os == 'windows-latest'
      with:
        name: compressionlib-binaries
        path: |
          compression\\bin\\compressionlib-${{ matrix.os }}-${{ matrix.platform }}.dll

    - name: archive unix-like
      uses: actions/upload-artifact@v2
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
      with:
        name: compressionlib-binaries
        path: |
          compression/bin/compressionlib-${{ matrix.os }}-${{ matrix.platform }}.so